### PR TITLE
Add ephemeral build for `dev-test`

### PR DESCRIPTION
**Pull request by vedantthapa**
Add ephemeral build for main branch. 

The endpoint for this deployment would be `main.dev.hopic-sdpac.phac-aspc.alpha.canada.ca` due to the fact that resources for ephemeral builds are modified based on the `${BRANCH_NAME}` variable and therefore the virtual service configuration ends up being - https://github.com/PHACDataHub/cpho-phase2/blob/be228da5c53fbe65ba4cdf9f72becb31d90f23c5/k8s/server/overlays/ephemeral/django/virtual-service.yaml#L7

Having `dev-test` would break this convention. Unless, we have a separate branch for `dev-test` and spin up an env based off of it.

### CODE REVIEW

**Review by Stephen-ONeil — CHANGES_REQUESTED** [review]
Confirm with Alex, but I believe what they want is a separate `dev-test` branch with an ephemeral environment, and probably no ephemeral environment for `main`. `main` is for staging code before releasing it by pushing to prod, and they might want to use `dev-test` for things that aren't ready to stage yet.

**Comment by vedantthapa** [comment]
> Confirm with Alex, but I believe what they want is a separate `dev-test` branch with an ephemeral environment, and probably no ephemeral environment for `main`. `main` is for staging code before releasing it by pushing to prod, and they might want to use `dev-test` for things that aren't ready to stage yet.

Ah, my bad!

@AlexCLeduc Before I make the necessary changes to this PR, could you please confirm this?

**Comment by AlexCLeduc** [comment]
Yes that is correct, 2 envs, one for prod and an ephemeral one for dev-test

**Review by Stephen-ONeil — APPROVED** [review]
:+1:

**Comment by vedantthapa** [comment]
Waiting for https://github.com/PHACDataHub/cpho-phase2/pull/216 to merge.

**Pull request merged**
