### PR TITLE
Remove `gcr-credentials-sync` job

### PR DESCRIPTION
**Pull request by vedantthapa**
Flux now supports [specifying OIDC authentication providers via `spec.provider` in an `ImageRepository` resource](https://fluxcd.io/flux/components/image/imagerepositories/#provider). Therefore, we no longer need the `gcr-credentials-sync` job to get / create the artifact registry credentials. Instead we use workload identity and annotate the `image-reflector-controller` to authenticate against the artifact registry.

### CODE REVIEW

**Review by Stephen-ONeil — APPROVED** [review]
Nice! Always a victory for the (surfaced) complexity to shrink, even if it's just by one resource :+1:

**Review by Stephen-ONeil — COMMENTED** [review]
Oh, but the yaml linter has a complaint looks like. Pre-approved for once that's passing, unless it some how requires non-cosmetic changes I guess.

**Comment by vedantthapa** [comment]
@Stephen-ONeil 
> Oh, but the yaml linter has a complaint looks like. Pre-approved for once that's passing, unless it some how requires non-cosmetic changes I guess.

yeah, that's in the `acm-core` repo. It's totally unrelated to our changes, however I've pushed a fix: https://github.com/PHACDataHub/acm-core/pull/227

**Comment by Stephen-ONeil** [comment]
> @Stephen-ONeil
> 
> > Oh, but the yaml linter has a complaint looks like. Pre-approved for once that's passing, unless it some how requires non-cosmetic changes I guess.
> 
> yeah, that's in the `acm-core` repo. It's totally unrelated to our changes, however I've pushed a fix: [PHACDataHub/acm-core#227](https://github.com/PHACDataHub/acm-core/pull/227)

:man_facepalming: my bad, no worries then, good to go!

**Review by simardeep1792 — APPROVED** [review]
LGTM !

**Pull request merged**
