### PR TITLE
feat: Add ephemeral environment django5

### PR DESCRIPTION
**Pull request by AlexCLeduc**
I copied the template and replaced the BRANCH_NAME with my targetted branch, `django5`

I need to test that my new branch doesn't mess with logging, because it's using a new version of structlog. I probably don't need much of a database.

A couple of questions,

1. Do I need to go and enable cloud-build, or is that only if I want to update this branch? If I push an update to this branch, it won't deploy anything?  
2. Is it important that my `django5` branch be ahead of prod? 
3. Will a new database be automatically created and migrated?
    - I presume no scripts are run beyond the plain migrate?
4. If I want to SSH in, can I use the server-management-session script ?

### CODE REVIEW

**Review by vedantthapa — APPROVED** [review]
LGTM!

> Do I need to go and enable cloud-build, or is that only if I want to update this branch? If I push an update to this branch, it won't deploy anything?

It'll be required if you want to use an image built off your branch (`django-5`) in the deployment. Currently it should use this image tag -https://github.com/PHACDataHub/cpho-phase2/blob/e65c1c9a01ba3a73c6543416e4d272e28a0af970/k8s/server/overlays/ephemeral/django/deployment.yaml#L10

You'll also need to update the `$imagepolicy` comment there to `flux-system:django5-server` as per [your image policy resource](https://github.com/PHACDataHub/cpho-phase2/pull/349/files#diff-13f4e15f6f7060125023379e4bf2f110e6d82f565700eb264a95f7770c4f2bf5R88), so that Flux can push a commit to update the image tag whenever it is available in the artifact registry. Here's some [docs](https://github.com/PHACDataHub/cpho-phase2/tree/django5/k8s#gotchas) around this. Also, don't forget to undo the cloudbuild changes.

Any updates for the deployment need to be made in the `django-5` branch. Since flux's [`GitRepository` resource points to that branch](https://github.com/PHACDataHub/cpho-phase2/pull/349/files#diff-13f4e15f6f7060125023379e4bf2f110e6d82f565700eb264a95f7770c4f2bf5R13-R14).

> Is it important that my django5 branch be ahead of prod?

It shouldn't matter for now as it's been a long time since we made any changes to server deployment spec so your branch's manifests should already be close to prod. In general, it's preferred to use the latest kubernetes manifests which are in prod. The `django5` looks like it already has it.

> Will a new database be automatically created and migrated?
I presume no scripts are run beyond the plain migrate?

Yep, a database cluster is automatically created from the most recent backup in the cloud storage bucket. However, you'll probably need to create a user to log in since SSO doesn't work on these deployments.

> If I want to SSH in, can I use the server-management-session script ?

Yes, I believe so. The scripts lists `server` pods across all namespaces so once the new pod is ready, it should come up as an option (alongside the prod pods) for you to SSH into. @Stephen-ONeil can you please fact-check me on this?

**Comment by Stephen-ONeil** [comment]
> Yes, I believe so. The scripts lists `server` pods across all namespaces so once the new pod is ready, it should come up as an option (alongside the prod pods) for you to SSH into. @Stephen-ONeil can you please fact-check me on this?

Yup, that's the idea!

**Comment by vedantthapa** [comment]
@AlexCLeduc Sorry I might've miscommunicated it, the changes in [52e3f08](https://github.com/PHACDataHub/cpho-phase2/pull/349/commits/52e3f0807b50340775cc3233481c72c95d22ae5d) need to be a part of your branch (`django-5`), not on this one 😅 .

Also, since we're soon going to merge in #330, I'd hold this off cause the domain where ephemeral envs is provisioned will be changed.

**Comment by AlexCLeduc** [comment]
Both changes, the imagepolicy and the cloud envs?

**Comment by vedantthapa** [comment]
> Both changes, the imagepolicy and the cloud envs?

Yep!

**Pull request merged**
